# These are supported funding model platforms.
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [Softradis]
patreon: empresarioMadri
ko_fi: softradis
custom:
  - https://github.com/Softradis/pixel-agents-web
